sudo: required

language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
- chmod +x gradlew

install:
- "./gradlew build jacocoTestReport --scan"

after_success:
- bash <(curl -s https://codecov.io/bash)

script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./gradlew bintrayUpload --scan; fi

env:
  global:
  - secure: zQIQcY79Qv1Z56jQZU+l9SlBMb7DlN3nqynaVRwZGqrX39KwyuGo/hWkkhyKFShtPyyKRUt4YbcCQw2BxV4iSM+4gBuHnmozwzoGWZPzwOSW3lNb+Ryowiy6+p/fkG1aygS2fSMexAPKCRZhirINpY6GrIVoJuqIwAeEv5+TqDdsVJNuN41UTY2EiQYvRwBcK1Ig7aBSoX/yirATivxLPWTnFuHoNR5Qu5Pc7Eb6uKpDRcA5f5lgRXEjyZ4ZLGHu6rpkl3XykIQqI999YjLBcqJpqZQ5md3u1KcsSTgTa7iilwteyjo+/YfTR4M6TAWCelmAbWrV0xOgOvpL90WqnnlLLHQCP0sdY4bz43b/n3q34lWz83WWhiuDLdhriT4H/pWLTjPmrHmuMYeJxBNVImghCWyOGh4E1UuLXD4i7+T+Hx6vkGFU4y1ZODqvu6vJot3yHYKDfYSiEwSXG47HmcM+kWFruzWpmbEM9wuINjaPPECdQM6P1KIJCyiUqsMmrAqmYMpdeqk2gk5G7Dtkv49hNxr91MdW4Nnw4gGWTGu99AiT8gsb/drTpzA9/S/7i57rOzZJhFYi3gQ12RUAp+LBVqBwC5Nj0hGqfvSMvJma+DLOKu1z4VTplwkTQCfLDuAbNLEzL45rz7oC8ccG38fxH2EA5NEVRz817UjuzJQ=
  - secure: IeBLtCTXWw74QH1UpSgJIROPDdf7ZjfR5vHIQhELVN2LDEygEJWLXuaS2JwvSQmdFQagg7WVx2KB4gK1nooq6nbPQBMeuN0K6Em/VS15vvjJuyFV7EjC+8ahJyPv6PgQMBcJwHzZ3kJphbi9xqjZNRNkY0Wk3xMRWyGGR0Y+hJXn79qV14gd34Ix7WKhIppnq0o7vXAtflY8/kFqW5fMl4Otgz5TpRawXh/AwS8yFNlTDjrUkb+pxTWmYqpdLYcVkzjRW9SL15w2Js13CDP1Kd/Ixs2nsapi1iV9h1TRg2Uo0ocUTPHCk7W2M9iYGMM+KleHnpi2BPc4QCu5WOl01rGalTcWt0esyXxTB9L66xXyBV9mJ+dqWatTXyM9x/01R4nbyZoBQKHvA0/8qV0bWr05edqVtyDb8uPxRTU7m3NXPDvk+UY/00kIYOYzUAMVGdoyPDoIwB6KXYxjC78yjerA3NpaRvs5M4uxHRe1kZm9IWHFzi/Fevfif18nc3lYG34dGiMkDp3C/z3GH/gk3xg0x2xoRKaf32KN5iHOoWFquXlUfkW953ineooTBHXmod8B8oNjmgxjEjmXszYcXxzQUkVpunsdogxxqepN2U5IsmnmLLhbMIo4fdLE53a/ZBcBIZ4adLjVTGcuDpNyxQST0Zw2wC33DDFEAoblkYo=
